# Generated by Django 5.1.3 on 2024-12-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style_personalization', '0001_initial'),
    ]

    operations = [
    ]
